盤面をキレイにととのえた
hyousen/igoappws pull request #1
Opened 2021-05-16 05:50 UTC by hyousen

2021-05-20 14:05 UTC, K-Shimo requested changes

2021-05-20 14:05 UTC, K-Shimo commented on board.rb
> +		if @board[@a][@b] == 0 then
boardの中身が"0"であることが、何を表しているのか、定数とかでわかりやすくした方が良いかも  
例えば 定数として
```ruby
NO_STONE = 0  
KURO = 1  
SHIRO = 2
```
とかに置くと、条件が `board[@a][@b] == NO_STONE` とかなって分かりやすくなるかもしれない  
(定数名は一例なので、最適な奴は考えてください)

2021-05-20 14:05 UTC, K-Shimo commented on board.rb
> +			if @tekazu % 2 == 1 then
ここもメソッドに切り出したほうがいいかな
例えば  
```ruby
def isBlack(tekazu)
      tekazu % 2 == 1  
end
```
として、そのメソッドを `if isBlack(@tekazu) then` とかしたほうが読みやすくなるような気がする

2021-05-20 14:05 UTC, K-Shimo commented on board.rb
>  				elsif column == 1 then
ここの大量の`if`はヤバイな…  
少なくとも、ここの`if` の条件はどうにか分かりやすくメソッドに切り出したほうがいいのと、  
`igoBoardEdgeImage.draw_rot()`がたくさんあるので、ラップメソッドを作ったほうがいいかも  
なんにせよ、もう少し見やすくできそう

あと、これだけ`if`が分岐するのは最初の作り方に問題がある可能性があるからクラスの構造とかを一度考えないとな…  
今は一旦置いておきましょう

2021-05-20 22:17 UTC, hyousen commented on board.rb
> +		if @board[@a][@b] == 0 then
とりあえず、
盤外を　　　　OUTSID_BOARD
石がない所を　BLANK_POINT
黒石を　　　　BLACK_STONE
白石を　　　　WHITE_STONE
にしてみたわ

2021-05-20 22:19 UTC, hyousen commented on board.rb
> +		if @board[@a][@b] == 0 then
ごめん、盤外は　　OUTSIDE_BOARD
でした。。。

2021-05-20 22:23 UTC, hyousen commented on board.rb
> +			if @tekazu % 2 == 1 then
メソッド実装したよ！
個人的にはreturnしなくても戻り値が返るのがちょっとした驚きだったわｗ

2021-05-20 22:26 UTC, hyousen commented on board.rb
>  				elsif column == 1 then
了解です。オイラもアクティビティ図とか書いてみてどれがベストか洗い出してみるわ！

2021-05-20 22:37 UTC, hyousen commented on board.rb
> +		if @board[@a][@b] == 0 then
<!--StartFragment-->
OUTSIDE_BOARD = -1
BLANK_POINT = 0
BLACK_STONE = 1
WHITE_STONE = 2
<!--EndFragment-->

2021-05-20 22:37 UTC, hyousen commented on board.rb
> +		if @board[@a][@b] == 0 then
みたいな感じにしました

2021-05-21 04:02 UTC, K-Shimo commented on board.rb
> +			if @tekazu % 2 == 1 then
`return`はつけ忘れたんだけど、返るんか笑

2021-05-21 12:14 UTC, hyousen commented on board.rb
>  				elsif column == 1 then
よー考えてみたら、マップ(盤面)を動的に配置するのがいけんかった気がする。
じゃけん、9路盤なら9路盤の背景をあらかじめ作っておいて、そこに石を置いたり消したりしたらええと思った。
じゃけん、とりあえず9路盤の背景画像を作ってみるわ！

2021-06-27 06:00 UTC, merged